name: MVC_MSbuild

on:
   push:

jobs:
  build:
  # env:
   # VSWhere_PATH: 'C:\GitHub_Runner\Saurabh\actions-runner-win-x64-2.284.0\_work\_tool\vswhere\2.7.1\x64\'
    #ACTIONS_ALLOW_UNSECURE_COMMANDS: true
   # MS_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe'
   
   runs-on: [self-hosted]

   steps:
    - name: Code Checkout
      uses: actions/checkout@v2
      
    - name: Zip actions
      uses: papeloto/action-zip@v1
      with:
          files: MVCDemo
          recursive: false
          dest: MVCDemo.zip
          
    - name: Move zip file
      run: move MVCDemo.zip C:\GitHub_Runner\Saurabh
